import { getLocaleOnServer } from '@/i18n/server'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const locale = getLocaleOnServer()
  return (
    <html lang={locale ?? 'vi'} className="h-full">
      <body>{children}</body>
    </html>
  )
}
